package clustering;

/**
 * Interface for ClusterAlg.
 *
 * @author Shalisa Pattarawuttiwong
 */
public interface ClusterAlg {

	/**
	 * Given instances (data), D = [x{0}, x{1}, ..., x{n-1}], a 
	 * similarity/distance measure, and number of clusters
	 * to generate, k > 0, partitions the data such that there are 
	 * C{0}, ..., C{k-1} clusters of D for some k.
	 */
    public void cluster();

    /**
     * Returns clusters [i{0}, ..., i{n-1}] where x{j} is a member of C{i{j}},
     * where C{0}, ..., C{k-1} are partitions of D. Invokes cluster()
     * if it has not previously been invoked, otherwise will return
     * clusters generated by the previous invocation of cluster().
     * @return assignment of instances of the dataset to clusters.
     */
    public int[] getClusters();

}
